export const ROUTES = {
  LANDINGPAGE: '/',
  LOGIN: '/',
  SIGN_UP: '/sign-up',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_IDENTITY: '/verify-identity',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CHAT: '/chat',
  DASHBOARD: '/dashboard',
  COMPLIANCE_GPT: '/dashboard/compliance-gpt',
  HISTORY: '/dashboard/history',
  TUTORIALS: '/dashboard/tutorials',
  BILLING: '/dashboard/billing',
  PROFILE: '/dashboard/profile',
  SUPSCRIPTION: '/dashboard/subscription',
  HELP_CENTER: '/help-center',
  TERMS: '/terms',
  PRIVACY: '/privacy',
} as const;
