export const ROUTES = {
  LANDINGPAGE: '/',
  LOGIN: '/auth',
  SIGN_UP: '/auth/sign-up',
  VERIFY_EMAIL: '/auth/verify-email',
  VERIFY_IDENTITY: '/auth/verify-identity',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  USER_AGGREMENT: '/auth/user-agreement',
  CHAT: '/chat',
  CHAT_ID: (id: string) => `/chat/${id}`,
  DASHBOARD: '/',
  RESOLVER: '/resolver',
  RESOLVER_ID: (id: string) => `/resolver/${id}`,
  COMPLIANCE_GPT: '/chat',
  HISTORY: '/history',
  TUTORIALS: '/tutorials',
  BILLING: '/billing',
  PROFILE: '/profile',
  SUPSCRIPTION: '/subscription',
  ENTERPRISE_SUBSCRIPTION: '/subscription/enterprise',
  HELP_CENTER: '/help-center',
  TERMS: '/terms',
  PRIVACY: '/privacy',
} as const;
